apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-qa
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  annotations:
    codefresh.io/product: demo2
spec:
  project: default
  destination:
    name: in-cluster
    namespace: demo-qa
  source:
    path: demo-applications/trioapp-qa
    repoURL: https://github.com/edaniels/codefresh-quickstart-demo.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=true
      - RespectIgnoreDifferences=false
